name       : terminology
version    : 1.11.0
release    : 3
source     :
    - https://download.enlightenment.org/rel/apps/terminology/terminology-1.11.0.tar.xz : 4fd884bd2ffbbc86d87163063074fbd969be04b17bb8d7e23cd1f6708fd86a2d
license    : BSD-2-Clause
component  : system.utils
summary    : This is an EFL terminal emulator with some extra bells and whistles.
description: |
    This is an EFL terminal emulator with some extra bells and whistles.
builddeps  :
    - pkgconfig(efl)
setup      : |
    %meson_configure -Dnls=true
build      : |
    %ninja_build
install    : |
    %ninja_install
