name       : terminology
version    : 1.13.0
release    : 7
source     :
    - https://download.enlightenment.org/rel/apps/terminology/terminology-1.13.0.tar.xz : 16a37fecd7bbd63ec9de3ec6c0af331cee77d6dfda838a1b1573d6f298474da5
homepage   : https://www.enlightenment.org/about-terminology
license    : BSD-2-Clause
component  : system.utils
summary    : This is an EFL terminal emulator with some extra bells and whistles
description: |
    Terminology is a terminal emulator for Linux/BSD/UNIX systems that uses EFL. It has a whole bunch of bells and whistles. Use it as your regular vt100 terminal emulator with all the usual features, such as 256 color support. Terminology is designed to emulate Xterm as closely as possible in most respects.
builddeps  :
    - pkgconfig(efl)
setup      : |
    %meson_configure -Dnls=true
build      : |
    %ninja_build
install    : |
    %ninja_install
