name       : terminology
version    : 1.9.0
release    : 1
source     :
    - https://download.enlightenment.org/rel/apps/terminology/terminology-1.9.0.tar.xz : 3f3bc327da5cc239d468570afed29a17e2fda3b1fee02b28f02ee7ed5141e46c
license    : BSD-2-Clause
component  : system.utils
summary    : This is an EFL terminal emulator with some extra bells and whistles.
description: |
    This is an EFL terminal emulator with some extra bells and whistles.
builddeps  :
    - pkgconfig(efl)
setup      : |
    %patch -p1 < $pkgfiles/0001-Switch-to-using-explicit-dependency-func-instead-of-.patch
    %meson_configure -Dnls=true
build      : |
    %ninja_build
install    : |
    %ninja_install
